name: notes
description: Notes Application
version: 1.0.1+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.3.2+3
  sqflite:
  path:
  intl: ^0.16.1
  auto_direction: ^0.0.4+1
  modal_bottom_sheet: ^1.0.0+1
  shared_preferences: ^0.5.12+4
  screenshot: ^0.2.0
  wc_flutter_share: ^0.2.2
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: arabic
      fonts:
            - asset: fonts/Tajawal.ttf

  uses-material-design: true